{
    "issue": {
        "title": "[Python] flake8 checks still not failing builds",
        "body": "***Note**: This issue was originally created as [ARROW-1711](https://issues.apache.org/jira/browse/ARROW-1711). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nI'm showing flake8 warnings in master, I'm not sure why these are still trickling through",
        "created_at": "2017-10-23T02:38:41.000Z",
        "updated_at": "2017-10-24T16:57:34.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: Python",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2017-10-24T16:57:34.000Z"
    },
    "comments": [
        {
            "created_at": "2017-10-23T16:42:30.496Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1711?focusedCommentId=16215427) by Uwe Korn (uwe):*\nAs a workaround we could switch to using `pytest-flake8` to run the flake8 check during the unit test exection. This should give us better reporting at the cost of later execution."
        },
        {
            "created_at": "2017-10-23T17:08:29.801Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1711?focusedCommentId=16215462) by Wes McKinney (wesm):*\nThe issue with this is that we are linting the Cython files separately. So we still need `flake8` to be able to fail the build. Will have to look more closely into it"
        },
        {
            "created_at": "2017-10-24T16:57:34.790Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1711?focusedCommentId=16217257) by Wes McKinney (wesm):*\nIssue resolved by pull request 1242\n<https://github.com/apache/arrow/pull/1242>"
        }
    ]
}