{
    "issue": {
        "title": "[CI] Python 3.6 build failure on Travis-CI",
        "body": "***Note**: This issue was originally created as [ARROW-3483](https://issues.apache.org/jira/browse/ARROW-3483). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nThis seems to have appeared recently:\r\nhttps://travis-ci.org/apache/arrow/jobs/439696079#L4242\r\n\r\n```Java\n\r\n-- Looking for python3.6m\r\n-- Found Python lib /home/travis/build/apache/arrow/pyarrow-test-3.6/lib/libpython3.6m.a\r\nCMake Error at cmake_modules/FindNumPy.cmake:62 (message):\r\n  NumPy import failure:\r\n  Traceback (most recent call last):\r\n    File \"/home/travis/build/apache/arrow/pyarrow-test-3.6/lib/python3.6/site-packages/numpy/core/__init__.py\", line 16, in <module>\r\n      from . import multiarray\r\n  ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such\r\n  file or directory\r\n```\r\n",
        "created_at": "2018-10-10T16:03:54.000Z",
        "updated_at": "2022-08-27T14:42:02.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: Continuous Integration",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2018-11-15T20:16:00.000Z"
    },
    "comments": [
        {
            "created_at": "2018-10-10T16:10:14.661Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-3483?focusedCommentId=16645190) by Uwe Korn (uwe):*\nThis output looks suspicious:\r\n\r\n```Java\n\r\nAdding pyarrow 0.11.1.dev49+gcd6e094 to easy-install.pth file\r\nInstalling plasma_store script to /home/travis/build/apache/arrow/pyarrow-test-2.7/bin\r\n\r\nInstalled /home/travis/build/apache/arrow/python\r\nProcessing dependencies for pyarrow==0.11.1.dev49+gcd6e094\r\nSearching for futures==3.2.0\r\nBest match: futures 3.2.0\r\nAdding futures 3.2.0 to easy-install.pth file\r\n\r\nUsing /home/travis/build/apache/arrow/pyarrow-test-2.7/lib/python2.7/site-packages\r\nSearching for six==1.11.0\r\nBest match: six 1.11.0\r\nAdding six 1.11.0 to easy-install.pth file\r\n\r\nUsing /home/travis/build/apache/arrow/pyarrow-test-2.7/lib/python2.7/site-packages\r\nSearching for numpy==1.15.2\r\nBest match: numpy 1.15.2\r\nAdding numpy 1.15.2 to easy-install.pth file\r\n```"
        },
        {
            "created_at": "2018-10-10T16:17:32.553Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-3483?focusedCommentId=16645201) by Antoine Pitrou (apitrou):*\nYes, the problem may be that we pip-install Numpy over the already conda-installed one.\r\nI'm trying to validate this hypothesis here: https://travis-ci.org/pitrou/arrow/builds/439718550"
        },
        {
            "created_at": "2018-10-10T16:51:24.487Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-3483?focusedCommentId=16645249) by Antoine Pitrou (apitrou):*\nThe hypothesis was wrong. The build fails when building Arrow, which is before pip-installing Numpy..."
        },
        {
            "created_at": "2018-10-10T16:59:39.450Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-3483?focusedCommentId=16645260) by Antoine Pitrou (apitrou):*\nBetween <https://travis-ci.org/apache/arrow/jobs/439602955> (green) and <https://travis-ci.org/apache/arrow/jobs/439696079> (red) the Python version changed from \"3.6.6-h5001a0f_0\" to \"3.6.6-h5001a0f_1\". Unfortunately I'm unable to understand what the corresponding conda-forge changeset is (I see build numbers like 1000 and 1001)."
        },
        {
            "created_at": "2018-10-10T17:25:03.133Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-3483?focusedCommentId=16645300) by Antoine Pitrou (apitrou):*\nIndeed it seems the build failure is fixed when downgrading to \"3.6.6-h5001a0f_0\":\r\nhttps://travis-ci.org/pitrou/arrow/builds/439743236#L2090\r\n"
        },
        {
            "created_at": "2018-10-10T17:26:57.431Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-3483?focusedCommentId=16645304) by Antoine Pitrou (apitrou):*\nLooks like this was already reported. Let's hope it gets fixed quickly.\r\nhttps://github.com/conda-forge/python-feedstock/issues/210"
        },
        {
            "created_at": "2018-11-15T20:14:52.569Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-3483?focusedCommentId=16688587) by Wes McKinney (wesm):*\nIs this still an issue? "
        },
        {
            "created_at": "2018-11-15T20:15:42.606Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-3483?focusedCommentId=16688588) by Antoine Pitrou (apitrou):*\nNo, it's gone."
        },
        {
            "created_at": "2022-08-27T14:42:02.322Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-3483?focusedCommentId=17586003) by @toddfarmer:*\nTransitioning issue from Resolved to Closed to based on resolution field value."
        }
    ]
}