{
    "issue": {
        "title": "[Python] flake8 warnings are not failing CI builds",
        "body": "***Note**: This issue was originally created as [ARROW-1430](https://issues.apache.org/jira/browse/ARROW-1430). Please see the [migration documentation](https://gist.github.com/toddfarmer/12aa88361532d21902818a6044fda4c3) for further details.*\n\n### Original Issue Description:\nI think this is because the flake8 calls are inside a bash function. We'll need to do a bit of work on our CI scripts to make sure the `set -e` results in flake8 call propagating the error code",
        "created_at": "2017-08-29T14:55:21.000Z",
        "updated_at": "2017-09-07T17:01:57.000Z",
        "labels": [
            "Migrated from Jira",
            "Component: Python",
            "Type: bug"
        ],
        "closed": true,
        "closed_at": "2017-09-07T17:01:57.000Z"
    },
    "comments": [
        {
            "created_at": "2017-09-06T19:25:40.885Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1430?focusedCommentId=16155911) by Wes McKinney (wesm):*\nPR: https://github.com/apache/arrow/pull/1059"
        },
        {
            "created_at": "2017-09-07T17:01:57.536Z",
            "body": "***Note**: [Comment](https://issues.apache.org/jira/browse/ARROW-1430?focusedCommentId=16157238) by Wes McKinney (wesm):*\nIssue resolved by pull request 1059\n<https://github.com/apache/arrow/pull/1059>"
        }
    ]
}